### ISSUE TITLE
filtered query returning no hits

### ISSUE THREAD

**Issue by giorgiacek** [younginnovations/resourcecontracts-elasticsearch#1]
Not very experienced with elastic search, but trying to run a filtered query, and I get no hits, but yesterday morning it used to work, how is that possible?

```
'{
"query": {
"filtered": {
 "query": {"term": { "signature_year": "2000"}},
  "filter": {
   "term": { "language": "english"}
      }
    }
  }
}'
```

(sorry for bad styling)

**Comment by adinuca** [comment]
Closing as the issue is too old.
