### ISSUE TITLE
Elasticsearch request problem /contract/metadata

### ISSUE THREAD

**Issue by gmagnai** [younginnovations/resourcecontracts-elasticsearch#4]
Hello. I have some issue. About send request to "/contract/metadata/".

But errors:

"\"id\" is not a valid parameter. Allowed parameters are: \"parent\", \"preference\", \"realtime\", \"refresh\", \"routing\", \"client\", \"custom\", \"filter_path\""

I dont know how exactly elasticsearch works. May be missed some configurations..

Also how it searches contracts in database?

**Comment by adinuca** [comment]
Closing as the issue is too old and we don't have steps to reproduce it.
